module.exports = {
    goodData: {
        test_1: {
            loanType: 'homePurchase',
            propertyType: 'singleFamilyHome',
            cityName: 'Boston, MA',
            propertyPurpose: 'primaryHome',
            newHome: 'yes',
            realEstateAgent: 'yes',
            estimatePurchasePrice: '100000',
            downPayment: '20000',
            creditScore: 'excellent',
            bankruptcyHistory: 'no',
            addressLine1: '12345',
            addressLine2: 'S Fox Ln',
            addressLine3: 'Boston, MA 02101',
            firstName: 'David',
            lastName: 'Escle',
            email: 'david.escle@gmail.com',
            nameOutput: 'David Escle',
            emailOutput: 'david.escle@gmail.com',
            loanTypeOutput: 'Home Purchase',
            propertyTypeOutput: 'Single Family Home',
            cityOutput: 'Boston, MA',
            propertyPurposeOutput: 'Primary Home',
            newHomeOutput: 'Yes',
            realEstateAgentOutput: 'Yes',
            estimatePurchasePriceOutput: '100000',
            downPaymentOutput: '20000',
            creditScoreOutput: 'Excellent',
            bankruptcyHistoryOutput: 'Has not been in bankruptcy or foreclosure',//no
            currentAddressOutput: {
                lineOne: '12345',
                lineTwo: 'S Fox Ln',
                lineThree: 'Boston, MA 02101'
            }
        },
        test_2: {
            loanType: 'refinance',
            propertyType: 'townHome',
            cityName: 'Provo, UT',
            propertyPurpose: 'rentalProperty',
            newHome: 'no',
            realEstateAgent: 'no',
            estimatePurchasePrice: '10000000',
            downPayment: '30000',
            creditScore: 'good',
            bankruptcyHistory: 'bankruptcy',
            addressLine1: '56789',
            addressLine2: 'N mad ln',
            addressLine3: 'Paris, FR 75000',
            firstName: 'Scrapy',
            lastName: 'Andrew',
            email: 'scrapyandrew@live.com',
            nameOutput: 'Scrapy Andrew',
            emailOutput: 'scrapyandrew@live.com',
            loanTypeOutput: 'Refinance',
            propertyTypeOutput: 'Town Home',
            cityOutput: 'Provo, UT',
            propertyPurposeOutput: 'Rental Property',
            newHomeOutput: 'No',
            realEstateAgentOutput: 'No',
            estimatePurchasePriceOutput: '10000000',
            downPaymentOutput: '30000',
            creditScoreOutput: 'Good',
            bankruptcyHistoryOutput: 'Has had bankruptcy',
            currentAddressOutput: {
                lineOne: '56789',
                lineTwo: 'N mad ln',
                lineThree: 'Paris, FR 75000'
            }
        }
        
        },
        badData : {
            test_3: {
                loanType: 'homeEquityLoanLine',
                propertyType: 'condo',
                cityName: 'Boston, MA',
                propertyPurpose: 'secondaryHome',
                newHome: 'yes',
                realEstateAgent: 'yes',
                estimatePurchasePrice: '220000',
                downPayment: '2000',
                estimatePurchasePrice1:'220000',
                downPayment1:'2000',
                creditScore: 'fair',
                bankruptcyHistory: 'foreclosure',
                addressLine1: '56789',
                addressLine2: 'N mad ln',
                addressLine3: 'Paris, FR 75000',
                firstName: 'Scrapy',
                lastName: 'Andrew',
                email: 'scrapyandrew@live.com',
                nameOutput: 'Scrapy Andrew',
                emailOutput: 'scrapyandrew@live.com',
                loanTypeOutput: 'Home Equity',
                propertyTypeOutput: 'Condo',
                cityOutput: 'Boston, MA',
                propertyPurposeOutput: 'Secondary Home',
                newHomeOutput: 'Yes',
                realEstateAgentOutput: 'Yes',
                estimatePurchasePriceOutput: '220000',
                downPaymentOutput: '2000',
                creditScoreOutput: 'Fair',
                bankruptcyHistoryOutput: 'Has had a foreclosure',
                currentAddressOutput: {
                    lineOne: '56789',
                    lineTwo: 'N mad ln',
                    lineThree: 'Paris, FR 75000' 
        }
        }
    
}
}
